### PR TITLE
Update setup.cfg

### PR DESCRIPTION
**Pull request by satra**
include data in the package.

### CODE REVIEW

**Comment by satra** [comment]
@cni-md - could you please check if this branch solves #2 ?

**Comment by effigies** [comment]
@satra I tried building the `sdist` with your fix, and it didn't work. Looking into the documentation, it appears that means to respect `MANIFEST.in`. Instead, I updated the `package_data` option, and that resolved it, at least locally. I pushed that to your branch.

Assuming this resolves @cni-md's issue, we should update the Python skeleton in `niflow-manager`.

**Comment by cni-md** [comment]
A pip install git+https://github.com/niflows/nipype1-workflows.git@fix/include-data did not work for me. It is compaining the missing setup.py in the main niflow folder.

> pip install git+https://github.com/niflows/nipype1-workflows.git@fix/include-data
Collecting git+https://github.com/niflows/nipype1-workflows.git@fix/include-data
  Cloning https://github.com/niflows/nipype1-workflows.git (to revision fix/include-data) to /scratch/spralat_dti/tmp/pip-req-build-twlqstpi
  Running command git clone -q https://github.com/niflows/nipype1-workflows.git /scratch/spralat_dti/tmp/pip-req-build-twlqstpi
  Running command git checkout -b fix/include-data --track origin/fix/include-data
  Switched to a new branch 'fix/include-data'
  Branch fix/include-data set up to track remote branch fix/include-data from origin.
    ERROR: Command errored out with exit status 1:
     command: /users/jstadler/studien/spralatP3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch/spralat_dti/tmp/pip-req-build-twlqstpi/setup.py'"'"'; __file__='"'"'/scratch/spralat_dti/tmp/pip-req-build-twlqstpi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /scratch/spralat_dti/tmp/pip-req-build-twlqstpi/pip-egg-info
         cwd: /scratch/spralat_dti/tmp/pip-req-build-twlqstpi/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/users/jstadler/studien/spralatP3/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/scratch/spralat_dti/tmp/pip-req-build-twlqstpi/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

`pip install -e /scratch/spralat_dti/tmp/pip-req-build-twlqstpi/package/setup.py `worked well

**Comment by effigies** [comment]
`pip install -e` isn't a good test, since it uses the repository itself as the installed directory, and the files are definitely there. Could you try:

```Shell
git clone -b fix/include-data https://github.com/niflows/nipype1-workflows.git
pip install nipype1-workflows/package
```

**Comment by cni-md** [comment]
@effigies Yes, this is working. Thanks a lot.

**Comment by effigies** [comment]
Great! Thanks for the confirmation.

**Pull request merged**
